# Floating Point Assignment

To run this notebook, use the provided file `floating_point_assignment.ipynb` and place it into your working directory.

```bash
source venv/bin/activate
jupyter lab --ip 0.0.0.0
```

Then, follow the link from the standard out of the command. This contains a token to provide you access. To turn in your work, save this notebook and provide the file.

# Definitions (25)

We will start with a definition of floating point and double using IEEE format definitions. They are

* 32-bit: 1 sign bit, 8 exp bits, 23 frac bits
* 64-bit: 1 sign bit, 11 exp bits, 52 frac bits
* 8-bit: 1 sign bit, 4 exp bits, 3 frac bits

1. Provide the representation of the value 3.14159265 in 32-bit IEEE format.
2. Provide the representation of the value 3.14159265 in 64-bit IEEE.
3. Provide the representation of the value 3.14159265 in the 8 bit format
4. Compare the precision loss of each value in comparison to 64-bit.
5. Choose a repeating number of your choosing (ie 1/3) and show the precision loss comparing the 8-bit format to 32-bit.

For numbers 1-3, provide your value in hex as that is easier. The above values should be completed by hand. You may use the techniques in part two to check your work.

For the hand calculations, a PDF will be attached along side this notebook. A python script showing each step for the mantissa will be at the
end in the discssion section.
1. 32-bit: 0x40490FDB
2. 64-bit: 0x400921FB53C8D4F1
3. 8-bit: 0x45

# Precision (25)

In [1]:
import numpy as np
from pymap3d.ecef import geodetic2ecef

In this section, you will use latitude, longitude, altitude coordinates to perform some calculations. The first is a coordinate change into Earth Centered, Earth Fixed (ECEF). You will then use a method for calculating the euclidean distance. You will then make observations on the precision of your calculations using three different floating point definitions. I have chosen UCCS and UC Boulder as examples. Replace at least one of these locations with those that you choose.

## Points (5 points each)

1. Replace location coordinates
2. Perform calculations with each of `np.float64`, `np.float32`, and `np.float16`
3. Brief discussion of observations

In [2]:
help(geodetic2ecef)

Help on function geodetic2ecef in module pymap3d.ecef:

geodetic2ecef(lat, lon, alt, ell: 'Ellipsoid' = Ellipsoid(model='wgs84', name='WGS-84 (1984)', semimajor_axis=6378137.0, semiminor_axis=6356752.31424518, flattening=0.0033528106647473664, thirdflattening=0.0016792203863836474, eccentricity=0.0818191908426201), deg: 'bool' = True) -> 'tuple'
    point transformation from Geodetic of specified ellipsoid (default WGS-84) to ECEF
    
    Parameters
    ----------
    
    lat
           target geodetic latitude
    lon
           target geodetic longitude
    alt
         target altitude above geodetic ellipsoid (meters)
    ell : Ellipsoid, optional
          reference ellipsoid
    deg : bool, optional
          degrees input/output  (False: radians in/out)
    
    
    Returns
    -------
    
    ECEF (Earth centered, Earth fixed)  x,y,z
    
    x
        target x ECEF coordinate (meters)
    y
        target y ECEF coordinate (meters)
    z
        target z ECEF coordinate (me

In [3]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix nor

### 64-bit

In [4]:
washingtonMonument_64 = np.array([38.8895, -77.0353, 9.144])
alcatraz_64 = np.array([37.8270,-122.4230, 41])

In [5]:
washingtonMonument_64_ecef = np.array([*geodetic2ecef(*washingtonMonument_64)])
washingtonMonument_64_ecef

array([ 1115257.47372751, -4844325.65541494,  3982782.00247558])

In [6]:
alcatraz_64_ecef = np.array([*geodetic2ecef(*alcatraz_64)])
alcatraz_64_ecef

array([-2704559.57842614, -4257924.95560529,  3890319.82103316])

In [7]:
np.linalg.norm(washingtonMonument_64_ecef - alcatraz_64_ecef)

np.float64(3865671.655438175)

### 32-bit

In [8]:
washingtonMonument_32 = washingtonMonument_64.astype(np.float32)
alcatraz_32 = alcatraz_64.astype(np.float32)

In [9]:
washingtonMonument_32_ecef = np.array([*geodetic2ecef(*washingtonMonument_32)])
washingtonMonument_32_ecef

array([ 1115257.4, -4844325. ,  3982781.8], dtype=float32)

In [10]:
alcatraz_32_ecef = np.array([*geodetic2ecef(*alcatraz_32)])
alcatraz_32_ecef

array([-2704559.8, -4257925. ,  3890319.8], dtype=float32)

In [11]:
np.linalg.norm(washingtonMonument_32_ecef - alcatraz_32_ecef)

np.float32(3865671.5)

### 16-bit

In [16]:
# Complete on your own
washingtonMonument_16 = washingtonMonument_32.astype(np.float16)
alcatraz_16 = alcatraz_32.astype(np.float16) 

In [17]:
washingtonMonument_16_ecef = np.array([*geodetic2ecef(*washingtonMonument_16)])
washingtonMonument_16_ecef

array([nan, nan, nan], dtype=float16)

In [18]:
alcatraz_16_ecef = np.array([*geodetic2ecef(*alcatraz_16)])
alcatraz_16_ecef

array([nan, nan, nan], dtype=float16)

In [19]:
np.linalg.norm(washingtonMonument_16_ecef - alcatraz_16_ecef)

np.float16(nan)

### Discussion

Provide a brief discussion here